version: 2
project_name: lazyss

before:
  hooks:
    - go mod tidy

builds:
  - id: lazyss
    main: ./cmd/lazyss
    binary: lazyss
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: lazyss
    ids:
      - lazyss
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

changelog:
  use: github
  sort: asc
