#!/usr/bin/env python3
import argparse
import pathlib
import re
import sys
from string import Template


ARCHIVE_RE = re.compile(
    r"^lazyss_.+_(?P<goos>darwin|linux)_(?P<goarch>amd64|arm64)\.tar\.gz$"
)
REQUIRED_TARGETS = (
    ("darwin", "amd64"),
    ("darwin", "arm64"),
    ("linux", "amd64"),
    ("linux", "arm64"),
)
SECRET_RE = re.compile(
    r"ghp_[A-Za-z0-9_]+|github_pat_[A-Za-z0-9_]+|AWS_SECRET_ACCESS_KEY|AWS_SESSION_TOKEN|"
    r"BEGIN (OPENSSH|RSA|EC|DSA) PRIVATE KEY|Authorization:\s*Bearer"
)


FORMULA_TEMPLATE = Template(
    '''# This file was generated by LazySS release automation. DO NOT EDIT.
class Lazyss < Formula
  desc "Terminal machine cockpit for SSH and AWS SSM"
  homepage "https://github.com/hmrdkn-labs/lazyss"
  version "$formula_version"
  license "MIT"

  on_macos do
    on_intel do
      sha256 "$darwin_amd64_sha"
      url "$darwin_amd64_url"
    end

    on_arm do
      sha256 "$darwin_arm64_sha"
      url "$darwin_arm64_url"
    end
  end

  on_linux do
    on_intel do
      sha256 "$linux_amd64_sha"
      url "$linux_amd64_url"
    end

    on_arm do
      sha256 "$linux_arm64_sha"
      url "$linux_arm64_url"
    end
  end

  def install
    bin.install "lazyss"
  end

  test do
    system "#{bin}/lazyss", "--version"
  end
end
'''
)


def read_checksums(path):
    checksums = {}
    for raw in pathlib.Path(path).read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line:
            continue
        digest, filename = line.split(maxsplit=1)
        checksums[filename] = digest.lower()
    return checksums


def formula_version(tag):
    return tag[1:] if tag.startswith("v") else tag


def archive_map(dist):
    found = {}
    for path in pathlib.Path(dist).iterdir():
        if not path.is_file():
            continue
        match = ARCHIVE_RE.match(path.name)
        if not match:
            continue
        found[(match.group("goos"), match.group("goarch"))] = path.name
    missing = [f"{goos}/{goarch}" for goos, goarch in REQUIRED_TARGETS if (goos, goarch) not in found]
    if missing:
        raise ValueError(f"missing formula archive(s): {', '.join(missing)}")
    return found


def render_formula(dist, tag, repo="hmrdkn-labs/lazyss"):
    dist = pathlib.Path(dist)
    checksums = read_checksums(dist / "checksums.txt")
    archives = archive_map(dist)
    values = {"formula_version": formula_version(tag)}

    for goos, goarch in REQUIRED_TARGETS:
        filename = archives[(goos, goarch)]
        checksum = checksums.get(filename)
        if checksum is None:
            raise ValueError(f"missing checksum for {filename}")
        key = f"{goos}_{goarch}"
        values[f"{key}_sha"] = checksum
        values[f"{key}_url"] = f"https://github.com/{repo}/releases/download/{tag}/{filename}"

    formula = FORMULA_TEMPLATE.substitute(values)
    if SECRET_RE.search(formula):
        raise ValueError("generated formula contains credential-like material")
    return formula


def generate(args):
    formula = render_formula(args.dist, args.version, args.repo)
    output = pathlib.Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(formula, encoding="utf-8")
    print(f"wrote {output}")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate the LazySS public Homebrew formula from GoReleaser dist output.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    generate_parser = subparsers.add_parser("generate", help="generate Formula/lazyss.rb")
    generate_parser.add_argument("--dist", default="dist")
    generate_parser.add_argument("--version", required=True, help="release tag, for example v0.1.0")
    generate_parser.add_argument("--repo", default="hmrdkn-labs/lazyss")
    generate_parser.add_argument("--output", default="dist/homebrew/Formula/lazyss.rb")
    generate_parser.set_defaults(func=generate)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except (OSError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
