import hashlib
import io
import importlib.util
import pathlib
import stat
import tarfile
import tempfile
import unittest
import zipfile


ROOT = pathlib.Path(__file__).resolve().parents[1]
MODULE_PATH = ROOT / "scripts" / "release_artifacts.py"


def load_module():
    spec = importlib.util.spec_from_file_location("release_artifacts", MODULE_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class ReleaseArtifactsTest(unittest.TestCase):
    def setUp(self):
        self.module = load_module()

    def write_dist(self, path, files):
        path.mkdir()
        lines = []
        for name, content in files.items():
            artifact = path / name
            artifact.parent.mkdir(parents=True, exist_ok=True)
            artifact.write_bytes(content)
            if name.endswith((".tar.gz", ".zip")):
                lines.append(f"{hashlib.sha256(content).hexdigest()}  {name}")
        (path / "checksums.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")

    def tar_archive(self, name="lazyss", mode=0o755, content=b"binary"):
        buffer = io.BytesIO()
        with tarfile.open(fileobj=buffer, mode="w:gz") as archive:
            info = tarfile.TarInfo(name)
            info.mode = mode
            info.size = len(content)
            archive.addfile(info, io.BytesIO(content))
        return buffer.getvalue()

    def zip_archive(self, name="lazyss.exe", content=b"windows-binary"):
        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, mode="w") as archive:
            archive.writestr(name, content)
        return buffer.getvalue()

    def complete_files(self):
        return {
            "lazyss_0.1.0_darwin_amd64.tar.gz": self.tar_archive(content=b"darwin-amd64"),
            "lazyss_0.1.0_darwin_arm64.tar.gz": self.tar_archive(content=b"darwin-arm64"),
            "lazyss_0.1.0_linux_amd64.tar.gz": self.tar_archive(content=b"linux-amd64"),
            "lazyss_0.1.0_linux_arm64.tar.gz": self.tar_archive(content=b"linux-arm64"),
            "lazyss_0.1.0_windows_amd64.zip": self.zip_archive(content=b"windows-amd64"),
            "lazyss_0.1.0_windows_arm64.zip": self.zip_archive(content=b"windows-arm64"),
        }

    def complete_files_with_cask(self):
        files = self.complete_files()
        files["homebrew/Casks/lazyss.rb"] = self.generated_cask(files).encode("utf-8")
        return files

    def generated_cask(self, files):
        checksums = {
            name: hashlib.sha256(content).hexdigest()
            for name, content in files.items()
            if name.endswith((".tar.gz", ".zip"))
        }
        return f'''# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyss" do
  require "download_strategy"

  class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
    def initialize(url, name, version, **meta)
      @url = url
      parse_url_pattern
      set_github_token
      meta[:headers] ||= []
      meta[:headers] << "Accept: application/octet-stream"
      meta[:headers] << "Authorization: Bearer #{{@github_token}}"
      ghurl = "https://api.github.com/repos/#{{@owner}}/#{{@repo}}/releases/assets/#{{asset_id}}"
      super(ghurl, name, version, **meta)
    end

    def set_github_token
      @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      raise CurlDownloadStrategyError, "HOMEBREW_GITHUB_API_TOKEN is required." unless @github_token
    end
  end

  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "{checksums["lazyss_0.1.0_darwin_amd64.tar.gz"]}"
      url "https://github.com/hamardikan/lazyss/releases/download/v0.1.0/lazyss_#{{version}}_darwin_amd64.tar.gz",
        verified: "github.com/hamardikan/lazyss/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "{checksums["lazyss_0.1.0_darwin_arm64.tar.gz"]}"
      url "https://github.com/hamardikan/lazyss/releases/download/v0.1.0/lazyss_#{{version}}_darwin_arm64.tar.gz",
        verified: "github.com/hamardikan/lazyss/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  on_linux do
    on_intel do
      sha256 "{checksums["lazyss_0.1.0_linux_amd64.tar.gz"]}"
      url "https://github.com/hamardikan/lazyss/releases/download/v0.1.0/lazyss_#{{version}}_linux_amd64.tar.gz",
        verified: "github.com/hamardikan/lazyss/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "{checksums["lazyss_0.1.0_linux_arm64.tar.gz"]}"
      url "https://github.com/hamardikan/lazyss/releases/download/v0.1.0/lazyss_#{{version}}_linux_arm64.tar.gz",
        verified: "github.com/hamardikan/lazyss/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  binary "lazyss"
end
'''

    def test_accepts_complete_archive_set_with_matching_checksums(self):
        with tempfile.TemporaryDirectory() as tmp:
            dist = pathlib.Path(tmp) / "dist"
            self.write_dist(dist, self.complete_files_with_cask())

            events = self.module.verify_dist(dist)

            self.assertEqual([event.level for event in events], ["ok", "ok", "ok", "ok", "ok"])
            self.assertIn("all required archives are present", events[0].message)

    def test_accepts_archive_set_only_when_host_binary_runs_version(self):
        original_host_target = self.module.host_target
        self.module.host_target = lambda: ("linux", "amd64")
        try:
            with tempfile.TemporaryDirectory() as tmp:
                dist = pathlib.Path(tmp) / "dist"
                files = self.complete_files()
                files["lazyss_0.1.0_linux_amd64.tar.gz"] = self.tar_archive(
                    content=b"#!/bin/sh\nprintf 'lazyss 0.1.0\\n'\n"
                )
                files["homebrew/Casks/lazyss.rb"] = self.generated_cask(files).encode("utf-8")
                self.write_dist(dist, files)

                events = self.module.verify_dist(dist, smoke_host_binary=True)

                self.assertEqual([event.level for event in events], ["ok", "ok", "ok", "ok", "ok", "ok"])
                self.assertIn("host archive binary responds to --version", events[-1].message)
        finally:
            self.module.host_target = original_host_target

    def test_rejects_archive_set_when_host_binary_cannot_start(self):
        original_host_target = self.module.host_target
        self.module.host_target = lambda: ("linux", "amd64")
        try:
            with tempfile.TemporaryDirectory() as tmp:
                dist = pathlib.Path(tmp) / "dist"
                files = self.complete_files()
                files["lazyss_0.1.0_linux_amd64.tar.gz"] = self.tar_archive(
                    mode=stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR,
                    content=b"#!/bin/sh\nexit 7\n",
                )
                files["homebrew/Casks/lazyss.rb"] = self.generated_cask(files).encode("utf-8")
                self.write_dist(dist, files)

                events = self.module.verify_dist(dist, smoke_host_binary=True)

                self.assertEqual(events[0].level, "fail")
                self.assertIn("host archive binary failed --version smoke", events[0].message)
        finally:
            self.module.host_target = original_host_target

    def test_rejects_missing_platform_archive(self):
        with tempfile.TemporaryDirectory() as tmp:
            dist = pathlib.Path(tmp) / "dist"
            files = self.complete_files_with_cask()
            files.pop("lazyss_0.1.0_windows_arm64.zip")
            self.write_dist(dist, files)

            events = self.module.verify_dist(dist)

            self.assertEqual(events[0].level, "fail")
            self.assertIn("missing required archive", events[0].message)
            self.assertIn("windows/arm64", events[0].message)

    def test_rejects_checksum_mismatch(self):
        with tempfile.TemporaryDirectory() as tmp:
            dist = pathlib.Path(tmp) / "dist"
            self.write_dist(dist, self.complete_files_with_cask())
            archive = dist / "lazyss_0.1.0_linux_amd64.tar.gz"
            archive.write_bytes(b"tampered")

            events = self.module.verify_dist(dist)

            self.assertEqual(events[0].level, "fail")
            self.assertIn("checksum mismatch", events[0].message)

    def test_rejects_missing_generated_cask(self):
        with tempfile.TemporaryDirectory() as tmp:
            dist = pathlib.Path(tmp) / "dist"
            self.write_dist(dist, self.complete_files())

            events = self.module.verify_dist(dist)

            self.assertEqual(events[0].level, "fail")
            self.assertIn("generated cask", events[0].message)

    def test_rejects_generated_cask_without_private_download_strategy(self):
        with tempfile.TemporaryDirectory() as tmp:
            dist = pathlib.Path(tmp) / "dist"
            files = self.complete_files_with_cask()
            files["homebrew/Casks/lazyss.rb"] = b'cask "lazyss" do\n  binary "lazyss"\nend\n'
            self.write_dist(dist, files)

            events = self.module.verify_dist(dist)

            self.assertEqual(events[0].level, "fail")
            self.assertIn("private download strategy", events[0].message)

    def test_rejects_generated_cask_with_wrong_archive_checksum(self):
        with tempfile.TemporaryDirectory() as tmp:
            dist = pathlib.Path(tmp) / "dist"
            files = self.complete_files_with_cask()
            cask = files["homebrew/Casks/lazyss.rb"].decode("utf-8")
            linux_checksum = hashlib.sha256(files["lazyss_0.1.0_linux_amd64.tar.gz"]).hexdigest()
            files["homebrew/Casks/lazyss.rb"] = cask.replace(linux_checksum, "0" * 64).encode("utf-8")
            self.write_dist(dist, files)

            events = self.module.verify_dist(dist)

            self.assertEqual(events[0].level, "fail")
            self.assertIn("missing cask checksum", events[0].message)

    def test_rejects_tar_archive_without_lazyss_binary(self):
        with tempfile.TemporaryDirectory() as tmp:
            dist = pathlib.Path(tmp) / "dist"
            files = self.complete_files()
            files["lazyss_0.1.0_linux_amd64.tar.gz"] = self.tar_archive(name="not-lazyss")
            files["homebrew/Casks/lazyss.rb"] = self.generated_cask(files).encode("utf-8")
            self.write_dist(dist, files)

            events = self.module.verify_dist(dist)

            self.assertEqual(events[0].level, "fail")
            self.assertIn("missing lazyss binary", events[0].message)
            self.assertIn("linux/amd64", events[0].message)

    def test_rejects_tar_archive_with_non_executable_lazyss_binary(self):
        with tempfile.TemporaryDirectory() as tmp:
            dist = pathlib.Path(tmp) / "dist"
            files = self.complete_files()
            files["lazyss_0.1.0_darwin_arm64.tar.gz"] = self.tar_archive(mode=0o644)
            files["homebrew/Casks/lazyss.rb"] = self.generated_cask(files).encode("utf-8")
            self.write_dist(dist, files)

            events = self.module.verify_dist(dist)

            self.assertEqual(events[0].level, "fail")
            self.assertIn("not executable", events[0].message)
            self.assertIn("darwin/arm64", events[0].message)

    def test_rejects_windows_archive_without_exe_binary(self):
        with tempfile.TemporaryDirectory() as tmp:
            dist = pathlib.Path(tmp) / "dist"
            files = self.complete_files()
            files["lazyss_0.1.0_windows_arm64.zip"] = self.zip_archive(name="lazyss")
            files["homebrew/Casks/lazyss.rb"] = self.generated_cask(files).encode("utf-8")
            self.write_dist(dist, files)

            events = self.module.verify_dist(dist)

            self.assertEqual(events[0].level, "fail")
            self.assertIn("missing lazyss.exe binary", events[0].message)
            self.assertIn("windows/arm64", events[0].message)


if __name__ == "__main__":
    unittest.main()
